//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by UniCheck.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_UNICHECK_FORM               101
#define IDR_MAINFRAME                   128
#define IDR_UNICHETYPE                  129
#define IDD_UNICHECK_OPTIONS            137
#define IDD_UNICHECK_SCANLIST           139
#define IDI_UPARROW                     141
#define IDI_DOWNARROW                   142
#define IDD_UNICHECK_COMMANDLINEPREV    144
#define IDD_UNICHECK_FILETYPELIST       145
#define IDD_UNICHECK_FILETYPE           146
#define IDC_MONITORWIN                  1000
#define IDC_MONITORFRM                  1001
#define IDC_FILETREE                    1008
#define IDC_ADDFILESBTN                 1009
#define IDC_VALIDATEBTN                 1010
#define IDC_ACTIONFRM                   1011
#define IDC_RESULTSBTN                  1013
#define IDC_OPTIONS_INSTALLATION        1020
#define IDC_OPTIONS_PROGAMPATH          1021
#define IDC_OPTIONS_PROGPATHLBL         1022
#define IDC_OPTIONS_BROWSEBTN           1023
#define IDC_ABOUT_CREDITSGROUPBOX       1024
#define IDC_OPTIONS_SOURCEPATH          1024
#define IDC_OPTIONS_PREFERENCES_GROUPBOX 1025
#define IDC_OPTIONS_SRCPATHLBL          1026
#define IDC_OPTIONS_BROWSESRCBTN        1027
#define IDC_OPTIONS_MAXFILESALLOWED     1028
#define IDC_OPTIONS_NUMFILESLBL         1029
#define IDC_OPTIONS_MAXFILESPIN         1030
#define IDC_OPTIONS_HEADERPATH          1031
#define IDC_SCANLIST                    1031
#define IDC_OPTIONS_HDRPATHLBL          1032
#define IDC_SCAN_TITLE                  1032
#define IDC_OPTIONS_BROWSEHDRBTN        1033
#define IDC_SCAN_TITLELBL               1033
#define IDC_OPTIONS_VIEWERPATHLBL       1034
#define IDC_SCAN_EXECUTABLELBL          1034
#define IDC_OPTIONS_VIEWERPATH          1035
#define IDC_SCAN_EXECUTABLE             1035
#define IDC_OPTIONS_BROWSEVWRBTN        1036
#define IDC_SCAN_BROWSEEXEBTN           1036
#define IDC_SCAN_RESULTSFILE            1037
#define IDC_SCAN_PROGGROUPBOX           1038
#define IDC_SCAN_RESULTSFILEGROUPBOX    1039
#define IDC_SCAN_FILENAMELBL            1040
#define IDC_SCAN_RESFILEPATHLBL         1041
#define IDC_OPTIONS_FSPATHLBL           1041
#define IDC_SCAN_RESULTSFILEPATH        1042
#define IDC_OPTIONS_FILESETPATH         1042
#define IDC_SCAN_BROWSERESBTN           1043
#define IDC_OPTIONS_BROWSEFSPBTN        1043
#define IDC_SCAN_PARAMSLISTBOX          1044
#define IDC_OPTIONS_FILESETFILENAME     1044
#define IDC_SCAN_PARAMETERSGROUPBOX     1045
#define IDC_SCAN_PARAMETER              1046
#define IDC_SCAN_PARAMEDITLBL           1047
#define IDC_SCAN_PARAMPATHLBL           1048
#define IDC_SCAN_PARAMPATH              1049
#define IDC_SCAN_BROWSEPARBTN           1050
#define IDC_SCAN_ENDSPCHKBX             1051
#define IDC_SCAN_TEMPFLDRSCHKBX         1052
#define IDC_SCAN_FILESETCHKBX           1053
#define IDC_SCAN_CMDCHKBX               1054
#define IDC_SCAN_SELFILECHKBX           1055
#define IDC_SCAN_USEPARAMPATHCHKBX      1056
#define IDC_UNICHECK_SCANSLISTBOX       1058
#define IDC_UNICHECK_SCANLIST_ADDBTN    1059
#define IDC_UNICHECK_SCANLIST_EDITBTN   1060
#define IDC_UNICHECK_SCANLIST_DELETEBTN 1061
#define IDC_SCAN_BASETYPESGROUPBOX      1062
#define IDC_SCAN_PARMADDUPDTBTN         1064
#define IDC_SCAN_EDITBTN                1065
#define IDC_SCAN_DELETEBTN              1066
#define IDD_UNICHECK_SCAN               1067
#define IDC_SCAN_ADJPARAMUP             1068
#define IDC_SCAN_ADJPARAMDOWN           1069
#define IDC_COMMANDLINEPREVIEW_COMMANDLINEEDIT 1069
#define IDC_UNICHECK_SCANLIST_PREVIEW   1071
#define IDC_OPTIONS_FSNAMELBL           1072
#define IDC_FILETYPELIST_TYPELISTBOX    1073
#define IDC_FILETYPELIST_ADDBUTTON      1074
#define IDC_FILETYPELIST_EDITBUTTON     1075
#define IDC_FILETYPELIST_DELETEBUTTON   1076
#define IDC_FILETYPE_FILETYPEEDIT       1077
#define IDC_FILETYPE_FILETYPEDESCEDIT   1078
#define IDC_FILETYPE_GROUPINGGROUPBOX   1079
#define IDC_FILETYPE_SOURCEGROUPRADIO   1080
#define IDC_FILETYPE_HEADERGROUPRADIO   1081
#define ID_TOOLS_OPTIONS                32771
#define ID_TOOLS_CLEARRECENTFILESLIST   32772
#define ID_TOOLS_CLEARRESULTSFILE       32773
#define ID_TOOLS_CLEARNOTIFICATIONPANE  32774
#define ID_EDIT_DELETE                  32775
#define ID_EDIT_ADDFILE                 32777
#define ID_VALIDATE_VIEWRESULTS         32781
#define ID_EDIT_RELOADFILE              32782
#define ID_VALIDATE_VALIDATE            32791
#define ID_TOOLS_SCANDEF                32793
#define ID_TOOLS_FILETYPES              32794

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
